language: elixir
elixir:
  - 1.10.3
otp_release:
  - 22.1.8
addons: # ensure that Travis-CI provisions a DB for our test:
  postgresql: '9.5'
env:
  - MIX_ENV=test
script: # run the tests:
  - mix cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
